import Head from "next/head";
import { GetStaticProps } from "next";
import { getProperties } from "@lib/fetchProperties";
import PropertyList from "@components/ui/propertyList";
import { Property } from "../types/property";

interface Props {
  properties: Property[];
}

const Home: React.FC<Props> = ({ properties }) => {
  return (
    <>
      <Head>
        <title>Property Listings</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="p-4 md:p-10 lg:p-12">
        <h1 className="text-xl md:text-4xl font-bold pb-2 md:pb-4 ">
          Property Listings
        </h1>
        <PropertyList initialProperties={properties} />
      </div>
    </>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const properties = await getProperties();
  return {
    props: {
      properties,
    },
  };
};
export default Home;
